### ISSUE TITLE
Predict question

### ISSUE THREAD

**Issue by AlejandraM97** [mundher/local-global#6]
I have a question Mr, Mundher @mundher. Why do you shorten the size of the predict and target vectors at the end of the predict function? Normally, do you use 255 to test, right? After you do that .view the data now is 86. Could you explain to me why?

`all_pred = all_pred.view(-1, 3).mean(dim=1)
all_targets = all_targets.view(-1, 3).mean(dim=1)`

**Comment by mundher** [comment]
That's because the actual size of the test in this fold is 86. And each of
these examples was augmented 3 times. Therefore, they became 256. However,
I just need to report the results for the 86 examples. So for each example,
I averaged its augmented versions as shown in the code.

If I took the average of all examples directly, I would give me different
results and it's wrong.

**Comment by AlejandraM97** [comment]
Now I understand, I was really confused about it, and it makes sense. Thank you very much!
